INSERT INTO Comparisons (name, prince2, pmbok, ipma, unifiedProcess, scrum)
VALUES ('Managed team', 0, 0, 0, 0, 0),
       ('Needs command and control', 1, 1, 1, 1, 3),
       ('Cooperative, transparent, self-organizing', 1, 1, 1, 1, 1),
       ('Distributed across locations', 1, 1, 1, 1, 3),
       ('Colocated', 1, 1, 1, 1, 1),
       ('Larger than 15 people', 1, 1, 1, 1, 3),
       ('Smaller than 15 people', 1, 1, 1, 2, 1),
       ('Company', 0, 0, 0, 0, 0),
       ('Requires detailed reporting', 1, 2, 2, 1, 2),
       ('Requires detailed documenting', 1, 2, 2, 1, 2),
       ('Has flat organization structure', 2, 1, 1, 1, 1),
       ('Has hierarchical organization structure', 1, 1, 1, 1, 2),
       ('Project', 0, 0, 0, 0, 0),
       ('Fast time to market', 2, 1, 1, 3, 1),
       ('Needs rapid customer feedback', 2, 1, 1, 3, 1),
       ('Complex and upredictable scope', 2, 1, 1, 3, 1),
       ('Large scope with span over 1 year', 1, 1, 1, 1, 3),
       ('Scope deliverable within 1 year', 1, 1, 1, 1, 1),
       ('Requirements unstable', 2, 1, 1, 2, 1),
       ('Requirements clearly defined upfront', 1, 1, 1, 1, 1),
       ('Domain - exploratory or innovation', 2, 1, 1, 2, 1),
       ('Domain - safety or critical', 1, 2, 2, 1, 3)